name: multilb malicious user detection and custom mitigation of waf security events
on:
  workflow_dispatch:
    inputs:
      msg: 
        description: 'configs'
        default: 'multilb-detection-custom-mitigation-waf'  
jobs:
  deploy:
  # This job deals with deployment of resources in F5 XC console and validate reachability of application
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dcarbone/install-jq-action@v1.0.1
      - name: Set environment variable
        run: echo "VES_P12_PASSWORD=$(jq -r .p12_file_pass user_inputs.json)" >> $GITHUB_ENV
      - name: Deploy infra
        run: |
          cp ./user_inputs.json https_malicious_user_detection_multilb/terraform.tfvars.json
          cd https_malicious_user_detection_multilb
          terraform init
          terraform plan -out=plan.out
          terraform apply -auto-approve plan.out
      - name: Upload tfstate file
        uses: actions/upload-artifact@v3
        with:
          name: tfstate
          path: https_malicious_user_detection_multilb/terraform.tfstate
      - name: Install python dependencies
        run: |
          python -m pip install requests
          python -m pip install requests[socks]
          python -m pip install requests[security]
          python -m pip install tqdm
          python -m pip install art
      - name: Run validation script
        run: python test_malicious_user.py secure True
      - name: Validate Deployment  
        run: |
           if [ ${{ env.EXIT }} == "true" ]; then echo "application deployment unsuccessful or application not reachable"; exit 1;\
           else echo "deployment is successful"; fi
  test:
  # This job deals with testing the deployed infra against malicious traffic and capture F5 XC malicious user logs
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Install python dependencies
        run: |
          python -m pip install requests
          python -m pip install requests[socks]
          python -m pip install requests[security]
          python -m pip install tqdm
          python -m pip install art
      - name: Run the test & Fetch XC logs
        run: python test_malicious_user.py xss
  destroy:
  # This job deals with destroying the created resources in F5 XC console
    if: ${{ always() }}
    needs: [deploy, test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download tfsate file
        uses: actions/download-artifact@v3
        with:
          name: tfstate
      - name: Set environment variable
        run: echo "VES_P12_PASSWORD=$(jq -r .p12_file_pass user_inputs.json)" >> $GITHUB_ENV
      - name: Destroy infra
        run: |
          cp ./user_inputs.json https_malicious_user_detection_multilb/terraform.tfvars.json
          mv ./terraform.tfstate ./https_malicious_user_detection_multilb/
          cd https_malicious_user_detection_multilb
          terraform init
          terraform plan -destroy 
          terraform destroy -auto-approve
